FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /app

COPY ./Jwt-service.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish

EXPOSE 8080

ENTRYPOINT ["dotnet", "./bin/Release/net10.0/Jwt-service.dll"]
